### ISSUE TITLE
Launchpad Pro v.1.0.1: Crash

### ISSUE THREAD

**Issue by michaelzehetleitner** [ericahrens/rhbitwig#11]
Hey Eric, thanks for making this script available. There are two issues, I'll create a separate Issue for them.

After updating to v 1.0.1, there is an error message that the launchpad drum sequencer crashed because it cannot invoke com.bitwig.extension.api.opensoundcontrol. ... Object[] because this.gridOSCconnection is null.

Any ideas?

Cheers,
Michael

**Comment by ericahrens** [comment]
Should be fixed with the latest Versions, for both Bitwig 4 and 5
